command: ['uvicorn', 'backend.main:app', '--host', '0.0.0.0', '--port', '$DATABRICKS_APP_PORT']

env:
  - name: GENIE_SPACE_ID
    value: "01f1a5808edd1859b78359723b7c5379"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "e39eb96b7df5ab0f"
  - name: PTM_CATALOG
    value: "workspace"
  - name: PTM_SCHEMA
    value: "policy_time_machine"
